# Generated by Django 2.2.1 on 2019-05-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190517_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='destination',
            new_name='city',
        ),
    ]
