# Generated by Django 2.2.1 on 2019-05-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190527_0231'),
        ('divesites', '0002_auto_20190517_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='City',
        ),
    ]
