# Generated by Django 2.2.1 on 2019-06-13 02:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0006_auto_20190528_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='max_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='divesite',
            name='max_temp_by_month',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='divesite',
            name='min_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='divesite',
            name='min_temp_by_month',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
