# Generated by Django 2.2.1 on 2019-06-13 02:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0007_auto_20190613_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
