CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(32) UNIQUE NOT NULL,
  password TINYTEXT NOT NULL
);

CREATE TABLE post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE location (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  parent INT DEFAULT NULL
);

CREATE TABLE site (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name TINYTEXT NOT NULL,
  location_id INT,
  coord POINT NOT NULL SRID 4326,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY (location_id) REFERENCES location (id)
);

CREATE TABLE note (
  id INT PRIMARY KEY AUTO_INCREMENT,
  content TEXT NOT NULL,
  site_id INT NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (site_id) REFERENCES site (id),
  FOREIGN KEY (user_id) REFERENCES user (id),
  UNIQUE(site_id, user_id)
);
