# Generated by Django 2.2.1 on 2019-06-04 02:12

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divelogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divelog',
            old_name='observations',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='divelog',
            name='divesite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='divesites.DiveSite'),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
